src/dynatrace-clients.ts

Trying to fix #9 with this PR.
Idea: Add an additional check whether the oauth client ID and secret can be used to authenticate against the Dynatrace SSO.
Example output when successful:
```
2025-05-08 09:51:42.940 [warning] [server stderr] Using SSO auth URL: https://sso.dynatrace.com/sso/oauth2/token
2025-05-08 09:51:43.068 [warning] [server stderr] Successfully retrieved token from SSO!
2025-05-08 09:51:43.069 [warning] [server stderr] Starting Dynatrace MCP Server...
2025-05-08 09:51:43.077 [warning] [server stderr] Connecting server to transport...
2025-05-08 09:51:43.078 [warning] [server stderr] Dynatrace MCP Server running on stdio
```
Example output when using an invalid oauth client:
```
2025-05-08 09:52:38.077 [warning] [server stderr] Using SSO auth URL: …
```

Improving authentication mechanism with better logging. Fixes #9

---

package-lock.json
package.json
src/dynatrace-clients.ts

We need to not throw an exception here, as the detail `response` (processed afterwards, hence we can not throw an Exception) of the oauth call contains concrete error messages, like
```
Error: Failed to retrieve OAuth token: invalid_request - Invalid OAuth2 request. UNSUCCESSFUL_OAUTH_ACCESS_TOKEN_VALIDATION_FAILED | OAuth client is missing following scopes [settings:objects:read]
```

Fix reporting of oauth issues like missing scope

---

src/index.ts
tsconfig.json

This PR addresses issue #46 by implementing version logging on server startup and using the dynamic version from package.json.
1. **Added version reading from package.json**: Uses `import` to import the package.json and extract the VERSION
2. **Log server version on startup**: Added `console.error(\`Starting Dynatrace MCP Server v\${VERSION}...\`)` for better troubleshooting
3. **Use dynamic version in McpServer constructor**: Replaced hardcoded '0.0.1' with the dynamic `VERSION` variable
4. **Removed TODO comment**: Cleaned up the TODO about reading version from package.json
- Uses `console.error` for logging to maintain consistency with the existing codebase and avoid interfering with STDIO
- Version is loaded once at startup for efficiency
- No breaking changes to the API or …

feat: log MCP server version on startup and use dynamic version

---

tsconfig.json

With https://github.com/dynatrace-oss/dynatrace-mcp/pull/47 and `resolveJsonModule` we accidentally changed the output structure (in the `dist/` folder).
Fixing tsconfig to keep the structure the same.
**how to verify**
```
rm -rf dist/
npm run build
```
should look like this:

chore: Fix tsconfig.json to include package.json

---

.gitignore
.vscode/mcp.json
src/authentication/dynatrace-clients.ts
src/authentication/types.ts
src/capabilities/call-app-function.ts
src/capabilities/get-ownership-information.ts
src/capabilities/send-slack-message.ts
src/index.ts

Refactoring :)
Moving things to where they belong, to prepare for #40

chore: Refactor dynatrace client into its own authentication sub-folder

---

CHANGELOG.md
src/index.ts

When querying [security events](https://docs.dynatrace.com/docs/discover-dynatrace/references/semantic-dictionary/model/security-events) we are getting an insufficient permission error:
Though the scope is added to the oauth client.
After a quick investigation I found that we are not requesting the scope.

fix: Added missing scope storage:security.events:read to executeDql

---

.dockerignore
.github/workflows/container.yml
Dockerfile

Added a Dockerfile for the MCP server, as well as build jobs. While we are not yet offering a container, we are planning to do so via the [Docker MCP Hub](https://hub.docker.com/u/mcp). In order for this to work, we need to provide a Dockerfile.
To build it:
```bash
docker build . -t dynatrace-mcp
```
You can test this locally, with the following `mcp.json`:
```json
{
"servers": {
"dynatrace-docker-mcp-server": {
"command": "docker",
"cwd": "${workspaceFolder}",
"args": [
"run",
"--rm",
"-i",
"--env-file",
"${workspaceFolder}/.env",
"dynatrace-mcp"
],
"envFile": "${workspaceFolder}/.env"
}
}
}
```

chore: Added Dockerfile for the MCP server

---

CHANGELOG.md
README.md
src/authentication/dynatrace-clients.test.ts
src/authentication/dynatrace-clients.ts
src/capabilities/call-app-function.ts
src/capabilities/create-workflow-for-problem-notification.ts
src/capabilities/execute-dql.ts
src/capabilities/find-monitored-entity-by-name.ts
src/capabilities/get-events-for-cluster.ts
src/capabilities/get-logs-for-entity.ts
src/capabilities/get-monitored-entity-details.ts
src/capabilities/get-ownership-information.ts
src/capabilities/get-problem-details.ts
src/capabilities/get-vulnerability-details.ts
src/capabilities/list-problems.ts
src/capabilities/list-vulnerabilities.ts
src/capabilities/send-slack-message.ts
src/capabilities/update-workflow.ts
src/getDynatraceEnv.test.ts
src/getDynatraceEnv.ts
src/index.ts

Added Preliminary Support for Platform Tokens (fixes #40).
Unfortunately, not all scopes are available for Platform Tokens. We might want to refactor some API Calls, but I'll defer that to later.
These are the changes I've done:
1. Refactored the whole authentication process, to no longer require the internal `_OAuthHttpClient`, and instead relying on the `PlatformHttpClient`.
2. Added a new environment variable `DT_PLATFORM_TOKEN`
3. Restructured README for Authentication and Scopes
I'm not too happy about the code in index.ts though, I think some refactoring for the authentication calls to create `dtClient` is needed.

feat: Added support for Platform Tokens. Fixes #40.

---

.vscode/mcp.json
README.md

With this PR, I'm adding an auto-reload feature to the local mcp server that we use in `.vscode/mcp.json`.
By leveraging the `--watch` command of Node, it will automatically reload once a change is detected in dist/index.js or the required files.
**Try it out**
* Open in VSCode
* Start the MCP Server via VSCode UI
* In a terminal Window, run `npm run watch`
* Make some changes to the code (e.g., add a new tool)
* Check if those changes get propagated by trying them out, e.g., via CoPilot

chore: Improved DevXP - added auto-reload to the local mcp server

---

.github/workflows/release.yml

Fixes failed release Workflow: https://github.com/dynatrace-oss/dynatrace-mcp/actions/runs/16479507541/job/46589802585
This was caused by [my PR](https://github.com/dynatrace-oss/dynatrace-mcp/pull/63/files#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3), where I changed from  `test` to `test:unit`, but forgot to do it in the release workflow.

chore: Fix release workflow running unit tests

---

CHANGELOG.md
README.md

The two scopes in question were never used, my recommendation is to remove them.

patch: Remove unneeded scopes

---

README.md

This is not the greatest PR in the world, no, this is a tribute.
To summarize the itsy-bitsy changes, _some_ of the headings ended with a period. A few others already used colons. To homogenize, I replaced them with a colon, but I can also be persuaded to remove trialing punctuation altogether.

chore: Fix typography in headings in README.md

---

CHANGELOG.md
src/index.ts

This should improve when and how often the verify_dql endpoint is called, as it's not needed when we get pre-verified queries.

patch: Improve verify_dql tool description

---

.husky/pre-commit
package-lock.json
package.json

Adding husky via Copilot
Fixes #88

chore: Added husky for pre-commit hooks

---

CHANGELOG.md
package-lock.json
package.json

Preparing release v0.5.0-rc.3
See CHANGELOG.md for details, but basically this contains the next step in converting the "old" `environment-api` calls to DQL statements.

chore: Prepare release v0.5.0-rc.3

---

.github/dependabot.yml

This should fix the message we are getting on dependabot PR:

chore: Remove reviewers and assignee from dependabot PRs

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/index.ts

Implemented HTTP Server mode based on https://www.npmjs.com/package/@modelcontextprotocol/sdk#streamable-http
Fixes #56 
Note: The code has been mostly generated using GH Copilot. Please be nit-picky!
**How to try it out**
* Start the server `npm run build && node dist/index.js --http`
* Add the following config to VSCode:
```
{
"servers": {
"my-mcp-server-c7ae031b": {
"url": "http://localhost:3000",
"type": "http"
}
},
"inputs": []
}
```
* Try it out in Copilot with Agent mode
**Screenshots**

patch: Added HTTP server mode

---

CHANGELOG.md
package-lock.json
package.json

Preparing the next and probably last release candidate for 0.5.0

chore: Prepare release v0.5.0-rc.4

---

.github/instructions/changelog.instructions.md
.github/prompts/release.prompt.md
README.md
src/authentication/dynatrace-clients.test.ts

This pull request introduces new documentation and improves test robustness for release and changelog processes, as well as for the Dynatrace client authentication logic. The main changes are grouped into documentation enhancements and test improvements.
**Documentation enhancements:**
* Added `.github/instructions/changelog.instructions.md` to provide clear style and content guidelines for changelog entries, ensuring consistency and user-focused release notes.
* Introduced `.github/prompts/release.prompt.md` with step-by-step instructions for preparing a release, including changelog management and versioning best practices.
**Test improvements:**
* Updated Dynatrace client authentication tests in `src/authentication/dynatrace-clients.test.ts` to use a flexible regular expression for …

chore: Add Copilot instructions and prompts for changelog and release flow

---

CHANGELOG.md
package-lock.json
package.json

This PR prepares the release for version 0.5.0.
- Updated CHANGELOG.md with version 0.5.0 section
- Moved all unreleased changes to the new version section with improved wording
- Updated package.json version from 0.5.0-rc.4 to 0.5.0
- Synced package-lock.json
Ready for review and merge to proceed with the release process.

chore(release): prepare for 0.5.0 release

---

CHANGELOG.md
README.md
integration-tests/execute-dql.integration.test.ts
src/capabilities/execute-dql.ts
src/capabilities/find-monitored-entity-by-name.ts
src/capabilities/get-monitored-entity-details.ts
src/capabilities/list-vulnerabilities.ts
src/index.ts

The goal is to alert the user when too many data are queried via `execute_dql`.
For now, we are logging and returning scanned bytes from the API, which the user can also find via DQL:
```
fetch dt.system.events
| filter event.kind == "QUERY_EXECUTION_EVENT" and contains(client.client_context, "dynatrace-mcp")
| fields timestamp, query_id, query_string, scanned_bytes, table, bucket, user.id, user.email, client.client_context
| sort timestamp desc
```
The result in the tool call:

feat: Added DQL Metadata like scannedBytes to execute_dql tool

---

.github/workflows/release.yml

**Note**: Depends on https://github.com/dynatrace-oss/dynatrace-mcp/pull/146  - will be rebased once the other PR got merged.
Within this PR, I've added the GitHub Action based publishing Workflow for publishing to the official MCP Registry, as detailed on https://github.com/modelcontextprotocol/registry/blob/main/docs/guides/publishing/github-actions.md

chore: Added MCP registry publishing workflows to GH actions

---

CHANGELOG.md
gemini-extension.json
package-lock.json
package.json
server.json
src/index.ts

With version 17 of `dotenv`, the author started printing messages to `stdout`, which is... not great.
We are now suppressing this messages by adding `quiet: true`, and handling any errors that might happen internally directly in our code. In addition, I'm writing what environment variables were loaded to `stderr` for troubleshooting purpose.

fix: Fixed an issue with MCP communication failing due to dotenv.

---

CHANGELOG.md
src/index.ts

In order to avoid unwanted and unauthorized sending of data, e.g., because of Prompt Injection, we are introducing a human in the loop. Furthermore, we are making sure that the message/body sent contains an information about sensitive data.
https://github.com/user-attachments/assets/68bd9379-655b-4ad7-bf3f-f0272a4fc499
Content-wise, this is what we get on the receiving end (no actual log data, just summaries! Awesome!)

feat: Added human-approval step for send-email, send-slack-message, create-workflow and make-workflow-public

---

CHANGELOG.md
src/capabilities/davis-copilot.ts
src/index.ts

The goal here is to provide some self-service information for end-users. We've seen this error appearing quite a bit on some environments.
To verify, I have disabled Davis Copilot on one environment, and tried it out manually:

patch: Provide a clearer error message in case Davis Copilot is not enabled (fixes #172)

---

CHANGELOG.md
src/capabilities/get-events-for-cluster.ts
src/index.ts

Also fixed the parameter `clusterId` and the respective DQL filter to use the Dynatrace Entity ID for Kubernetes Clusters (else, you wouldn't find the cluster events).

patch: Added a limit to get_kubernetes_events

---

.github/workflows/release.yml
server.json

* GH Actions changes from: https://github.com/modelcontextprotocol/registry/blob/main/docs/guides/publishing/github-actions.md
* server.json changes from: https://github.com/modelcontextprotocol/registry/blob/main/docs/reference/server-json/CHANGELOG.md#server-json-schema-changelog

chore: Fixing publishing to anthropic mcp registry

---

.github/workflows/release.yml

The docs on https://github.com/modelcontextprotocol/registry/blob/main/docs/guides/publishing/github-actions.md are wrong, they don't work. Now trying with version 1.2.3, which should work 🤞

chore: Fix MCP Publisher again
